// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: core/blast/v1/type/blast.type.proto

package blastv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmailCredentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SmtpHost string `protobuf:"bytes,1,opt,name=smtp_host,json=smtpHost,proto3" json:"smtp_host,omitempty"`
	SmtpPort int32  `protobuf:"varint,2,opt,name=smtp_port,json=smtpPort,proto3" json:"smtp_port,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *EmailCredentials) Reset() {
	*x = EmailCredentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_blast_v1_type_blast_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmailCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailCredentials) ProtoMessage() {}

func (x *EmailCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_core_blast_v1_type_blast_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailCredentials.ProtoReflect.Descriptor instead.
func (*EmailCredentials) Descriptor() ([]byte, []int) {
	return file_core_blast_v1_type_blast_type_proto_rawDescGZIP(), []int{0}
}

func (x *EmailCredentials) GetSmtpHost() string {
	if x != nil {
		return x.SmtpHost
	}
	return ""
}

func (x *EmailCredentials) GetSmtpPort() int32 {
	if x != nil {
		return x.SmtpPort
	}
	return 0
}

func (x *EmailCredentials) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *EmailCredentials) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type WhatsAppCredentials struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	SenderId    string `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
}

func (x *WhatsAppCredentials) Reset() {
	*x = WhatsAppCredentials{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_blast_v1_type_blast_type_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhatsAppCredentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhatsAppCredentials) ProtoMessage() {}

func (x *WhatsAppCredentials) ProtoReflect() protoreflect.Message {
	mi := &file_core_blast_v1_type_blast_type_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhatsAppCredentials.ProtoReflect.Descriptor instead.
func (*WhatsAppCredentials) Descriptor() ([]byte, []int) {
	return file_core_blast_v1_type_blast_type_proto_rawDescGZIP(), []int{1}
}

func (x *WhatsAppCredentials) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *WhatsAppCredentials) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

var File_core_blast_v1_type_blast_type_proto protoreflect.FileDescriptor

var file_core_blast_v1_type_blast_type_proto_rawDesc = []byte{
	0x0a, 0x23, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x62, 0x6c, 0x61, 0x73, 0x74, 0x2f, 0x76, 0x31, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x2f, 0x62, 0x6c, 0x61, 0x73, 0x74, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x62, 0x6c, 0x61, 0x73, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x84, 0x01, 0x0a, 0x10, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x43, 0x72,
	0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61, 0x6c, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6d, 0x74,
	0x70, 0x5f, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6d,
	0x74, 0x70, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6d, 0x74, 0x70, 0x5f, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x73, 0x6d, 0x74, 0x70, 0x50,
	0x6f, 0x72, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x55, 0x0a, 0x13, 0x57,
	0x68, 0x61, 0x74, 0x73, 0x41, 0x70, 0x70, 0x43, 0x72, 0x65, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x61,
	0x6c, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72,
	0x49, 0x64, 0x42, 0xbb, 0x01, 0x0a, 0x11, 0x63, 0x6f, 0x6d, 0x2e, 0x62, 0x6c, 0x61, 0x73, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x42, 0x0e, 0x42, 0x6c, 0x61, 0x73, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x40, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6e, 0x6b, 0x65, 0x69, 0x30, 0x31, 0x30, 0x37,
	0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x62, 0x6c,
	0x61, 0x73, 0x74, 0x2d, 0x6d, 0x6f, 0x64, 0x6f, 0x6c, 0x75, 0x65, 0x2f, 0x62, 0x6c, 0x61, 0x73,
	0x74, 0x2f, 0x76, 0x31, 0x3b, 0x62, 0x6c, 0x61, 0x73, 0x74, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x42,
	0x56, 0x54, 0xaa, 0x02, 0x0d, 0x42, 0x6c, 0x61, 0x73, 0x74, 0x2e, 0x56, 0x31, 0x2e, 0x54, 0x79,
	0x70, 0x65, 0xca, 0x02, 0x0d, 0x42, 0x6c, 0x61, 0x73, 0x74, 0x5c, 0x56, 0x31, 0x5c, 0x54, 0x79,
	0x70, 0x65, 0xe2, 0x02, 0x19, 0x42, 0x6c, 0x61, 0x73, 0x74, 0x5c, 0x56, 0x31, 0x5c, 0x54, 0x79,
	0x70, 0x65, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02,
	0x0f, 0x42, 0x6c, 0x61, 0x73, 0x74, 0x3a, 0x3a, 0x56, 0x31, 0x3a, 0x3a, 0x54, 0x79, 0x70, 0x65,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_core_blast_v1_type_blast_type_proto_rawDescOnce sync.Once
	file_core_blast_v1_type_blast_type_proto_rawDescData = file_core_blast_v1_type_blast_type_proto_rawDesc
)

func file_core_blast_v1_type_blast_type_proto_rawDescGZIP() []byte {
	file_core_blast_v1_type_blast_type_proto_rawDescOnce.Do(func() {
		file_core_blast_v1_type_blast_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_blast_v1_type_blast_type_proto_rawDescData)
	})
	return file_core_blast_v1_type_blast_type_proto_rawDescData
}

var file_core_blast_v1_type_blast_type_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_blast_v1_type_blast_type_proto_goTypes = []any{
	(*EmailCredentials)(nil),    // 0: blast.v1.type.EmailCredentials
	(*WhatsAppCredentials)(nil), // 1: blast.v1.type.WhatsAppCredentials
}
var file_core_blast_v1_type_blast_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_core_blast_v1_type_blast_type_proto_init() }
func file_core_blast_v1_type_blast_type_proto_init() {
	if File_core_blast_v1_type_blast_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_blast_v1_type_blast_type_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EmailCredentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_blast_v1_type_blast_type_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*WhatsAppCredentials); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_blast_v1_type_blast_type_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_core_blast_v1_type_blast_type_proto_goTypes,
		DependencyIndexes: file_core_blast_v1_type_blast_type_proto_depIdxs,
		MessageInfos:      file_core_blast_v1_type_blast_type_proto_msgTypes,
	}.Build()
	File_core_blast_v1_type_blast_type_proto = out.File
	file_core_blast_v1_type_blast_type_proto_rawDesc = nil
	file_core_blast_v1_type_blast_type_proto_goTypes = nil
	file_core_blast_v1_type_blast_type_proto_depIdxs = nil
}
